function handle_dataset_request() {
	//Handle a data request from the page generated by HtmlFormWriter.
	
	//Get the URL of this page and truncate it at the "html" extension
	var url = document.URL; //TODO: vs window.location.href ?
	var index = url.indexOf(".html"); //TODO: if not found, bigger problems
	url = url.substring(0,index);
	
	//Get the output format (suffix) from the "output" select element.
	//Default to csv.
	var suffix = document.getElementById("output").value;
	if (suffix.length == 0) suffix = "csv";		
	url += "."+suffix+"?"; //TODO: only include "?" if there will be constraints, no biggie

	//Get the number of variable range/value choosers.
	//There will be one form for each var.
	var nvar = document.forms.length;
	for (var ivar=0; ivar<nvar; ivar++) {
		var form = document.forms[ivar];
		//TODO: assumeing range, support value, with checkbox for nearest
		var x1 = form.elements[0].value;
		var x2 = form.elements[1].value;
		var vname = form.name; //TODO: name vs id?
		//add constraint only if a value was entered
		//TODO: "inclusive" check box?
		if (x1.length != 0) url += "&"+vname+">="+x1;
		if (x2.length != 0) url += "&"+vname+"<="+x2;
	}

	window.location.assign(url);
}
